#!/usr/bin/env bun
/* vim: set filetype=typescript : */

import { $ } from "bun";

const ffmpeg = "ffmpeg";
const params = ["-hide_banner", "-i"];
const file = Bun.argv.slice(2)[0] || "/tmp/Videos/wife.mp4";

const fileExists = await Bun.file(file).exists();

if (!fileExists) {
  console.error(`${file}: no such file or directory`);
  process.exit(1);
}

const { stderr, exitCode } = await $`${ffmpeg} ${params} ${file}`.quiet();

const duration = (stderr.toString() as string).match(
  /Duration:\s(\d\d:\d\d:\d+\.\d+)/,
)?.[1];

console.log("Duration:", duration);
console.log("Exit code:", exitCode);
